apiVersion: v1
kind: ReplicationController
metadata:
  name: aspnetapp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: aspnetapp
    spec:
      containers:
      - name: aspnetapp
        image: gcr.io/devops-gke/aspnetapp:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: aspnetapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: aspnetapp 
